# Configuración del Servidor
spring.application.name=ms-auth
server.port=8084

# Configuración de Base de Datos PostgreSQL (Puerto 5435 según tu Docker)
spring.datasource.url=jdbc:postgresql://localhost:5435/db_auth
spring.datasource.username=postgres
spring.datasource.password=Admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Clave secreta para firmar los JWT (Esta debe ser larga y segura)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#configurado para durar exactamente 24 horas (1 día)
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html