services:
  postgres-ruteo:
    image: postgres:16
    container_name: postgres-ruteo
    environment:
      POSTGRES_DB: db_ruteo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - ruteo_data:/var/lib/postgresql/data

volumes:
  ruteo_data: