server:
  port: 8086

spring:
  application:
    name: ms-ruteo

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5437/db_ruteo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html