name: CI LogiFlow Flota

on:
  push:
    branches: [ "development", "main" ]
  pull_request:
    branches: [ "development", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # CRÍTICO: SonarCloud necesita el historial completo para analizar código nuevo vs viejo

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build y Análisis Estático con SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub lo provee automáticamente
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # El secreto que configuró tu compañero
        run: |
          mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=jsmena5_Proyecto-Arquitectura-LogiFlow-Coronado-Mena-Panata \
          -Dsonar.organization=jsmena5 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
          -f ms-flota-restA/pom.xml

      - name: Notificar a Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *🚀 Reporte LogiFlow - ESPE*
            *Microservicio:* `ms-flota-rest`
            *Estado:* `${{ job.status == 'success' && '✅ ÉXITO' || '❌ FALLO' }}`
            *Rama:* `${{ github.ref_name }}`
            *Autor:* Michael Coronado
            
            *📊 Análisis de Calidad:* SonarCloud Ejecutado
            *Enlace:* [Ver logs de GitHub Actions](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})