name: Pipeline Unificado SonarCloud

on:
  push:
    branches: [ "development", "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ 'ms-flota-restA', 'ms-taller-restdos' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: |
          cd ${{ matrix.service }}
          mvn clean test

  analisis-sonarcloud:
    name: Analisis SonarCloud
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Analisis ms-flota
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=jsmena5_Proyecto-Arquitectura-LogiFlow-Coronado-Mena-Panata \
          -Dsonar.organization=jsmena5 \
          -Dsonar.host.url=https://sonarcloud.io \
          -f ms-flota-restA/pom.xml
      - name: Analisis ms-taller
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=jsmena5_Proyecto-Arquitectura-LogiFlow-Coronado-Mena-Panata-taller \
          -Dsonar.organization=jsmena5 \
          -Dsonar.host.url=https://sonarcloud.io \
          -f ms-taller-restdos/pom.xml

  notificacion-telegram:
    name: Notificar a Telegram
    needs: analisis-sonarcloud
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje de Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *🚀 Reporte LogiFlow - ESPE*
            *Estado del Pipeline:* `${{ job.status == 'success' && '✅ ÉXITO' || '❌ FALLO' }}`
            *Rama:* `${{ github.ref_name }}`
            *Autor:* ${{ github.actor }}
            
            *📊 Análisis:* [Ver reporte en SonarCloud](https://sonarcloud.io/dashboard?id=jsmena5_Proyecto-Arquitectura-LogiFlow-Coronado-Mena-Panata)
            *Logs:* [Ver ejecución en GitHub](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})